// Generated by scripts/build_showcase_atlas.py. Do not edit by hand.
export default {
 "columns": 6,
 "rows": 6,
 "cell": 512,
 "panels": [
  {
   "id": "travel-china-fuxing-high-speed-rail-network-map",
   "href": "travel/china-fuxing-high-speed-rail-network-map.png",
   "title": "China high-speed rail network map, lines in service",
   "collection": "Travel",
   "aspect": 1.333333,
   "uv": [
    0.000163,
    0.020996,
    0.166341,
    0.124674
   ]
  },
  {
   "id": "everything-llm-4-best-practices-for-claude-opus-4-7",
   "href": "everything-llm/4-best-practices-for-claude-opus-4-7.jpg",
   "title": "Four best practices for Claude Opus 4.7 xhigh mode",
   "collection": "Everything LLM",
   "aspect": 0.55814,
   "uv": [
    0.203613,
    0.000163,
    0.092773,
    0.166341
   ]
  },
  {
   "id": "everything-llm-gpt-5-series-pricing-evolution",
   "href": "everything-llm/gpt-5-series-pricing-evolution.png",
   "title": "GPT-5 series pricing evolution, Aug 2025 to Apr 2026",
   "collection": "Everything LLM",
   "aspect": 1.5,
   "uv": [
    0.333496,
    0.027995,
    0.166341,
    0.110677
   ]
  },
  {
   "id": "everything-llm-gpt-5-6-sol-the-first-5-days",
   "href": "everything-llm/gpt-5-6-sol-the-first-5-days.png",
   "title": "GPT-5.6 Sol: 11 changes and rollbacks in the first five days",
   "collection": "Everything LLM",
   "aspect": 0.666667,
   "uv": [
    0.527995,
    0.000163,
    0.110677,
    0.166341
   ]
  },
  {
   "id": "claude-tag-claude-tag-01-what-it-is",
   "href": "claude-tag/claude-tag-01-what-it-is.png",
   "title": "A teammate in the channel",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.666829,
    0.036621,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-02-vs-coding-agent",
   "href": "claude-tag/claude-tag-02-vs-coding-agent.png",
   "title": "Single-player tool vs. team member",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.833496,
    0.036621,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-03-long-horizon",
   "href": "claude-tag/claude-tag-03-long-horizon.png",
   "title": "Long-horizon execution",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.000163,
    0.203288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-04-system-architecture",
   "href": "claude-tag/claude-tag-04-system-architecture.png",
   "title": "Runtime architecture",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.166829,
    0.203288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-05-context-layer",
   "href": "claude-tag/claude-tag-05-context-layer.png",
   "title": "The context layer",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.333496,
    0.203288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-06-memory-layer",
   "href": "claude-tag/claude-tag-06-memory-layer.png",
   "title": "Three scopes of memory",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.500163,
    0.203288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-07-request-lifecycle",
   "href": "claude-tag/claude-tag-07-request-lifecycle.png",
   "title": "One mention, end to end",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.666829,
    0.203288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-08-proactive-context",
   "href": "claude-tag/claude-tag-08-proactive-context.png",
   "title": "Ambient context, unprompted work",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.833496,
    0.203288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "claude-tag-claude-tag-09-memory-core",
   "href": "claude-tag/claude-tag-09-memory-core.png",
   "title": "Memory core (dark variant)",
   "collection": "Claude Tag",
   "aspect": 1.777778,
   "uv": [
    0.000163,
    0.369954,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "ai-buzzword-loop-engineering",
   "href": "ai-buzzword/loop-engineering.jpeg",
   "title": "Loop Engineering: build the loop, stay the engineer",
   "collection": "AI Buzzword",
   "aspect": 1.777778,
   "uv": [
    0.166829,
    0.369954,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "ai-buzzword-trendslop-when-al-gives-you-buzzwords-instead-of",
   "href": "ai-buzzword/trendslop-when-al-gives-you-buzzwords-instead-of.png",
   "title": "Trendslop: when AI gives you buzzwords instead of strategy",
   "collection": "AI Buzzword",
   "aspect": 0.75,
   "uv": [
    0.354329,
    0.333496,
    0.124674,
    0.166341
   ]
  },
  {
   "id": "the-claude-code-leak",
   "href": "claude-code/the-claude-code-leak.jpeg",
   "title": "The Claude Code leak: three release-process gaps",
   "collection": "Claude Code",
   "aspect": 0.746667,
   "uv": [
    0.521322,
    0.333496,
    0.124023,
    0.166341
   ]
  },
  {
   "id": "how-claude-code-leaked",
   "href": "claude-code/how-claude-code-leaked.jpeg",
   "title": "How Claude Code leaked: the safe path vs. what happened",
   "collection": "Claude Code",
   "aspect": 1.791667,
   "uv": [
    0.666829,
    0.37028,
    0.166341,
    0.092773
   ]
  },
  {
   "id": "claude-code-shortcuts-cheatsheet",
   "href": "claude-code/shortcuts-cheatsheet.jpeg",
   "title": "Claude Code cheat sheet: commands, shortcuts, workflow",
   "collection": "Claude Code",
   "aspect": 1.791667,
   "uv": [
    0.833496,
    0.37028,
    0.166341,
    0.092773
   ]
  },
  {
   "id": "claude-code-prong-my-claude-code-buddy",
   "href": "claude-code/prong-my-claude-code-buddy.jpg",
   "title": "Prong, my Claude Code buddy",
   "collection": "Claude Code",
   "aspect": 1.791667,
   "uv": [
    0.000163,
    0.536947,
    0.166341,
    0.092773
   ]
  },
  {
   "id": "people-lead-lifecycle-activities",
   "href": "people-lead-lifecycle/activities.png",
   "title": "People Lead cycle, onboarding to offboarding",
   "collection": "People Lead lifecycle",
   "aspect": 2.64514,
   "uv": [
    0.166829,
    0.551921,
    0.166341,
    0.062826
   ]
  },
  {
   "id": "kloburste-gebrauchsanleitung",
   "href": "daily-laughs/klobu-rste-gebrauchsanleitung.jpg",
   "title": "Klobürste Gebrauchsanleitung: ganz falsch bis ganz richtig",
   "collection": "Daily laughs",
   "aspect": 1.419446,
   "uv": [
    0.333496,
    0.52474,
    0.166341,
    0.117188
   ]
  },
  {
   "id": "fde-04-iceberg-bright-dark-line-en",
   "href": "fde/04-iceberg-bright-dark-line-en.png",
   "title": "What the client says vs. what actually decides the project",
   "collection": "Forward Deployed Engineer",
   "aspect": 1.776833,
   "uv": [
    0.500163,
    0.536621,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "fde-05-four-translation-steps-craft",
   "href": "fde/05-four-translation-steps-craft.png",
   "title": "Business translation: four steps from client words to shippable AI",
   "collection": "Forward Deployed Engineer",
   "aspect": 1.776833,
   "uv": [
    0.666829,
    0.536621,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "fde-06-bento-whole-frame-craft",
   "href": "fde/06-bento-whole-frame-craft.png",
   "title": "The hardest part of AI projects isn't technology",
   "collection": "Forward Deployed Engineer",
   "aspect": 1.776833,
   "uv": [
    0.833496,
    0.536621,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "fable5-21days-infographic-craft-handmade",
   "href": "fable5-21days/infographic-craft-handmade.png",
   "title": "21 days of building with agents: project-by-project breakdown",
   "collection": "Fable5 21Days",
   "aspect": 0.5625,
   "uv": [
    0.036621,
    0.666829,
    0.093424,
    0.166341
   ]
  },
  {
   "id": "fable5-21days-infographic-cyberpunk",
   "href": "fable5-21days/infographic-cyberpunk.png",
   "title": "21 days of building with agents: effort ranked by project",
   "collection": "Fable5 21Days",
   "aspect": 1.776833,
   "uv": [
    0.166829,
    0.703288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "fable5-21days-infographic-densemodules-morandi",
   "href": "fable5-21days/infographic-densemodules-morandi.png",
   "title": "21 days of building with agents: full report, vitals to top skills",
   "collection": "Fable5 21Days",
   "aspect": 0.562799,
   "uv": [
    0.369954,
    0.666829,
    0.093424,
    0.166341
   ]
  },
  {
   "id": "fable5-21days-infographic-hubspoke-edu",
   "href": "fable5-21days/infographic-hubspoke-edu.png",
   "title": "21 days of building with agents: hub-and-spoke map of the work",
   "collection": "Fable5 21Days",
   "aspect": 1.777778,
   "uv": [
    0.500163,
    0.703288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "fable5-21days-infographic-roadmap-watercolor",
   "href": "fable5-21days/infographic-roadmap-watercolor.png",
   "title": "21 days of building with agents: the journey, week by week",
   "collection": "Fable5 21Days",
   "aspect": 1.776833,
   "uv": [
    0.666829,
    0.703288,
    0.166341,
    0.093424
   ]
  },
  {
   "id": "ai-native-organisation-the-new-engineering-org-the-human-side-v1",
   "href": "ai-native-organisation/the-new-engineering-org-the-human-side-v1.png",
   "title": "Architect and Operator: the new engineering org and the human side (v1)",
   "collection": "AI Native Organisation",
   "aspect": 1.791667,
   "uv": [
    0.833496,
    0.703613,
    0.166341,
    0.092773
   ]
  },
  {
   "id": "ai-native-organisation-the-new-engineering-org-the-human-side-v2",
   "href": "ai-native-organisation/the-new-engineering-org-the-human-side-v2.png",
   "title": "Architect and Operator: the new engineering org and the human side (v2)",
   "collection": "AI Native Organisation",
   "aspect": 1.791667,
   "uv": [
    0.000163,
    0.87028,
    0.166341,
    0.092773
   ]
  },
  {
   "id": "product-builder-peter-steinberger-on-human-taste-1",
   "href": "product-builder/peter-steinberger-on-human-taste-1.png",
   "title": "Peter Steinberger on human taste: taste plus system design",
   "collection": "Product Builder",
   "aspect": 0.707579,
   "uv": [
    0.191243,
    0.833496,
    0.117513,
    0.166341
   ]
  },
  {
   "id": "product-builder-peter-steinberger-on-human-taste-2",
   "href": "product-builder/peter-steinberger-on-human-taste-2.png",
   "title": "Peter Steinberger on human taste: notes from the AI Engineer keynote",
   "collection": "Product Builder",
   "aspect": 0.666667,
   "uv": [
    0.361328,
    0.833496,
    0.110677,
    0.166341
   ]
  },
  {
   "id": "product-builder-jenny-wen-design-process-is-dead",
   "href": "product-builder/jenny-wen-design-process-is-dead.jpeg",
   "title": "The design process is dead: Jenny Wen on Lenny's Podcast",
   "collection": "Product Builder",
   "aspect": 0.750293,
   "uv": [
    0.520996,
    0.833496,
    0.124674,
    0.166341
   ]
  }
 ]
};
